### ISSUE TITLE
Making home page more appealing and responsive

### ISSUE THREAD

**Issue by Aaryanb45** [4darsh-Dev/CogniGaurd#100]
making the page more attractive as it is very much basic and also adding dark mode to make it more appealing.
Also adding new features in home page like hover so that it can look better and also works on the css of the homepage.#VSOC24

**Comment by 4darsh-Dev** [comment]
okay @Aaryanb45  sounds great, 
You can propose the design preview or share SS for the changes you want. 
i'll assign difficulty level after seeing contribution impact.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
Hey @Aaryanb45 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
