### ISSUE TITLE
Making Login and Register Page More Responsive and Attractive 

### ISSUE THREAD

**Issue by AkshatPandey-2004** [4darsh-Dev/CogniGaurd#101]
Hey!!!!
just a enhancement that your website has basic template of login and register page...

#What i can do.....
I will make your website more responsive and attractive by using css and js 
And i can also add few animation..

**Comment by 4darsh-Dev** [comment]
sure @AkshatPandey-2004  assigned to you. 
Propose the design preview or share SS of changes you want, 
Be sure other contributors are working on this too, so you need to be more efficient.

**Comment by 4darsh-Dev** [comment]
@AkshatPandey-2004 any work update?

**Comment by 4darsh-Dev** [comment]
looks nice @AkshatPandey-2004, 
just pic some nice vector/ image instead of this one, you can visit freepik 
https://www.freepik.com/search?format=search&last_filter=query&last_value=login+&query=login+

you can also pick animated ones or 3D icons
https://iconscout.com

**Comment by 4darsh-Dev** [comment]
Hey @AkshatPandey-2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
