### ISSUE TITLE
[Bug]: Abouts Page Is Not Responsive

### ISSUE THREAD

**Issue by shreyash3087** [4darsh-Dev/CogniGaurd#102]
**Describe the bug**
The Abouts Page of CogniGaurd Wesbite is not Responsive.

**To Reproduce**
1. Go to 'Cognigaurd' wesbite - https://cogni-gaurd.vercel.app/
2. Click on 'Abouts'
3. Decrease the Screen Width
4. Notice The Overflow of Text

**Expected behavior**
It should be Responsive to all screen widths

**Screenshots**

![Screenshot (34)](https://github.com/4darsh-Dev/CogniGaurd/assets/72603662/425a0434-4301-4170-96ef-39dc9b2889ac)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
[X] I am a VSoC Contributor.
**Email** - Shreyash3087@gmail.com

**Comment by 4darsh-Dev** [comment]
@shreyash3087 the design of about page is looking too odd, 
it would be better if you implement a better design then you can add responsiveness using appropriate css media queries in about.css 
be sure to make changes in django-web-app

**Comment by 4darsh-Dev** [comment]
Hey @shreyash3087 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Hey @shreyash3087 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
