### ISSUE TITLE
[FEAT]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [4darsh-Dev/CogniGaurd#108]
### Currently, there is an issue template for this repo, but no issue form which will help users in contributing.

- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/apu52/METAVERSE/assets/73957207/4c6889aa-3abf-485d-9c41-09f1f562a0aa)

- and issue templates:

![image](https://github.com/apu52/METAVERSE/assets/73957207/6827e4a8-5382-4376-bbf6-afb9f9731252)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for Closing of Contribution period for GSSoC 24'
 Finish your work and raise the PRs ASAP to get your points. 
 Thanks💗 for your valuable Contributions!

**Comment by 4darsh-Dev** [comment]
Hey @TonyStark-47 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
