### ISSUE TITLE
Feat: Adding a 404 notfound page for the website

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [4darsh-Dev/CogniGaurd#111]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/125277258/bdab872a-53a8-4607-96d1-62aef876cdb1)

**Describe the solution you'd like**
we can handle it using some images or gifs

**Describe alternatives you've considered**

**Additional context**

**Comment by 4darsh-Dev** [comment]
okay @RamakrushnaBiswal, 
assigned to you, 
Propose the design first, Make sure you're page is responsive
I'll add a blank 404 page with the route after design approval.

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/125277258/ece88308-37e3-45b1-9e6c-8e79ba2b5215)

**Comment by RamakrushnaBiswal** [comment]
@4darsh-Dev how is it

**Comment by 4darsh-Dev** [comment]
@RamakrushnaBiswal it good, 
but looking very basic, try adding some vectors, animated gifs or images to make it attractive 
reference : https://dribbble.com/search/404

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/125277258/d8d53f72-0526-4324-a1e3-59e92ae17168)

**Comment by RamakrushnaBiswal** [comment]
hi @4darsh-Dev I think this looks good like professional website

**Comment by 4darsh-Dev** [comment]
@RamakrushnaBiswal  yes much better,
be sure to read contributing guidelines, and readme and local setup pinned in issues as notice, 
Read them carefully, 
1. Ensure your web page is responsive across mobile and iPad devices use media queries

**Comment by 4darsh-Dev** [comment]
I'll add an html , css and js file named as custom_404  and routes soon,
There you can write your code .

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
@RamakrushnaBiswal i've recently added custom 404 page routes, 
file name :  django-web-app/templates/custom_404.html
you can modify it, 
Be sure to read contributing guidelines, local project setup notice pinned in issues section and readme. to avoid deployment related errors

**Comment by RamakrushnaBiswal** [comment]
solved

**Comment by 4darsh-Dev** [comment]
Hey @RamakrushnaBiswal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
