### ISSUE TITLE
Cross icon needs to be fixed

### ISSUE THREAD

**Issue by kapilG0** [4darsh-Dev/CogniGaurd#116]
**Describe the bug**
Cross icon needs to be fixed

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot_20240625_234153](https://github.com/4darsh-Dev/CogniGaurd/assets/59639410/155fcb80-b846-4a29-a5ef-fd5e390d2aa4)
.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kapilG0** [comment]
Hello @4darsh-Dev please assign this issue to me under gssoc 24

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
@kapilG0  Describe the change your want in cross icon

**Comment by kapilG0** [comment]
> @kapilG0 Describe the change your want in cross icon

As you can see in alignment cross icon not aligned properly

**Comment by 4darsh-Dev** [comment]
@kapilG0 it's has been done for design purpose

**Comment by kapilG0** [comment]
Ok sorry I was thinking by mistake it has done you can close thank you
