### ISSUE TITLE
WANT TO ADD DEEPFAKE DETECTION OF VIDEO , USING TRAINED MODEL

### ISSUE THREAD

**Issue by AbheetHacker4278** [4darsh-Dev/CogniGaurd#118]
**Is your feature request related to a problem? Please describe.**

### Deepfake Videos are major challenge in todays world , so i introduce my Deepfake detection model using Resnext50 and LSTM NN Model using Python(Django), HTML , CSS , JS.

**DeepFake Detection using Res-Next50 model which is been trained using various
datasets like , Celeb-Df Dataset , FaceForensics++ Dataset , Challenge Dataset , which can do
Sequential analyse of the video by dividing the video into 20 parts and analyse those parts on
the basis of face tone , color , replaced face structrure(nose , eyes , mouth).**

**Describe the solution you'd like**
### Can Easily Tell Which Video is FAKE or REAL

**Describe alternatives you've considered**
### I Want to add Seperate Section in Navbar for Deepfake detection

**Additional context**

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by AbheetHacker4278** [comment]
@4darsh-Dev please assign this issue to ME under GSSOC24

**Comment by 4darsh-Dev** [comment]
@AbheetHacker4278  you've good idea, 
but our solution doesn't align with deepfake detection 
if you want to contribute, 
1. we can work on fine-tuning a deep learning model for object detection to find visual based dark pattern
using CNN or something. 
2. A model also needed using  OCR,  Text Extraction from images 
These include changing button sizes, color , or just removing the cross button itself, 
## Visual Dark pattern sample
<img width="818" alt="Screenshot 2024-01-17 182455" src="https://github.com/4darsh-Dev/CogniGaurd/assets/109789509/e9b7f4b3-8259-4f09-91d4-fc2b49e641cd">

**Comment by AbheetHacker4278** [comment]
@4darsh-Dev , okay I respect your views , so i think we can start working on this project , for OCR  which can extract  button sizes, color , etc.

**Comment by AbheetHacker4278** [comment]
@4darsh-Dev we can use BeautifulSoap to parse HTML and extract text content from the elements and preprocess the extracted text to remove unnecessary characters, whitespace, and noise , using OCR

**Comment by 4darsh-Dev** [comment]
sure @AbheetHacker4278 you can look for security bugs in the website.
Feel free to share your views on improving the security.

**Comment by 4darsh-Dev** [comment]
Hey @AbheetHacker4278 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
