### ISSUE TITLE
Add feature to view the password

### ISSUE THREAD

**Issue by AkhilaSunesh** [4darsh-Dev/CogniGaurd#119]
**Is your feature request related to a problem? Please describe.**
Location: login and sign-up page
Users are unable to look into their password
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/140897461/68f13837-70a5-43fe-a05b-5e7127533e28)

**Describe the solution you'd like**
An eye toggle buttons helps to resolve this issue.
kindly assign this issue to me

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
@AkhilaSunesh asssigned to you, 
Go through contributing.md guidelines and local project setup pinned in issues section

**Comment by 4darsh-Dev** [comment]
@AkhilaSunesh  any work update?

**Comment by AkhilaSunesh** [comment]
yeah, will submit it today.

**Comment by 4darsh-Dev** [comment]
Hey @AkhilaSunesh ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
