### ISSUE TITLE
Animation to images

### ISSUE THREAD

**Issue by Damini2004** [4darsh-Dev/CogniGaurd#123]
**Is your feature request related to a problem? Please describe.**
user engagement increases
**Describe the solution you'd like**
enhancing user attention
**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/119414762/f9ce6b5a-e1f5-4f47-9607-f8668d7fb454)

**Comment by 4darsh-Dev** [comment]
@Damini2004 our ui has been updated recently, 
Check it now for possible mods

**Comment by 4darsh-Dev** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
