### ISSUE TITLE
Rebuild the logo for Cognigaurd

### ISSUE THREAD

**Issue by Dharmi-dev** [4darsh-Dev/CogniGaurd#126]
The logo of Cognigaurd can be improved.
the improvement could contain, more simplicity and clearity with little touch of modern designing
Hope you would like to go through this small issue.

**Comment by Dharmi-dev** [comment]
As a UI/UX and logo designer I am very excited to work with you to solving this issue
Please assign this issue to me.

**Comment by 4darsh-Dev** [comment]
@Dharmi-dev  pls check our recent website first, 
see for possible mods/addn

**Comment by 4darsh-Dev** [comment]
Hey @Dharmi-dev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
Hey @Dharmi-dev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
