### ISSUE TITLE
Newsletter Section Addition

### ISSUE THREAD

**Issue by Damini2004** [4darsh-Dev/CogniGaurd#128]
**Is your feature request related to a problem? Please describe.**
Adding the newsletter section in the footer of the website where user get regular update.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/119414762/5220d2fb-eccd-4f01-85c2-690dd87e1c61)

**Comment by 4darsh-Dev** [comment]
assigned to you @Damini2004

**Comment by 4darsh-Dev** [comment]
any work update @Damini2004 ?

**Comment by Damini2004** [comment]
Yes wanted to work but facing difficulity in setup the backend process any video for setup ?

**Comment by 4darsh-Dev** [comment]
@Damini2004 you can go through, readme 
one contributor has also faced same difficulty, 
I've explained each step in conversation, go through it 
#138 
let me know any errors, with SS ..

**Comment by 4darsh-Dev** [comment]
or simply if you are working on frontend, 
just get the HTML from dango-web-app/templates
CSS and js code which is linked to that HTML from static folder, 

comment the code involving the dango HTML syntax, 
test and make changes to code
uncomment the django HTML syntax..

**Comment by 4darsh-Dev** [comment]
Hey @Damini2004 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
