### ISSUE TITLE
Adding a  small section/space to let user message 

### ISSUE THREAD

**Issue by Garima-149** [4darsh-Dev/CogniGaurd#135]
@4darsh-Dev I would like to add a space to let user message the organization with its email.Please assign me with this issue.
![Screenshot (98)](https://github.com/4darsh-Dev/CogniGaurd/assets/143211271/bcac20c1-b3f3-4130-8936-b033ceadcad8)

**Comment by 4darsh-Dev** [comment]
assigned to you @Garima-149

**Comment by Garima-149** [comment]
![IMG_20240717_183458.jpg](https://github.com/user-attachments/assets/3e673fdb-e1aa-417e-922f-1b5d38f43af2)

@4darsh-Dev  please check?

**Comment by 4darsh-Dev** [comment]
@Garima-149  it's fine just remove colon 
and add some padding to input box, 
dont' forget to add <a mailto: .... /a> anchor tag instead of a button
and use font awesome send icon

**Comment by 4darsh-Dev** [comment]
are you planning to create a single PR for all assigned issues, ?

**Comment by Garima-149** [comment]
Yes @4darsh-Dev

**Comment by 4darsh-Dev** [comment]
okay then you'll get a level3 for it

**Comment by 4darsh-Dev** [comment]
no need to download you can use it as web component, 
it will be free, using these will  help you providing more control for animation and effects.

**Comment by Garima-149** [comment]
@4darsh-Dev ok I will try

**Comment by Garima-149** [comment]
![IMG_20240717_223816.jpg](https://github.com/user-attachments/assets/35b40308-dfe1-46e8-965e-bf17a6aae033)

@4darsh-Dev All changes done

**Comment by 4darsh-Dev** [comment]
okay @Garima-149  👍🏻

**Comment by 4darsh-Dev** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
