### ISSUE TITLE
Changing color of web scroll bar

### ISSUE THREAD

**Issue by Garima-149** [4darsh-Dev/CogniGaurd#136]
@4darsh-Dev I would like to  change the color web scroll bar.
![Screenshot (97)](https://github.com/4darsh-Dev/CogniGaurd/assets/143211271/36bf3f4a-48f6-48e7-be8c-89c411990405)
Please assign me with this issue.

Currently,it is light gray and according to background theme of  website,it could be changed to in accordance of background color.

**Comment by 4darsh-Dev** [comment]
assigned to you @Garima-149

**Comment by ruthwikchikoti** [comment]
like to work on this

**Comment by 4darsh-Dev** [comment]
already assigned @ruthwikchikoti , 
No issues, find some more aspects to work on visit our site link :

**Comment by 4darsh-Dev** [comment]
or you can ask from @Garima-149 if she allows ?

**Comment by Garima-149** [comment]
@4darsh-Dev Is this color works good for UI?
![Screenshot (111)](https://github.com/user-attachments/assets/93897612-d716-4962-b8df-308cf61c6d45)

**Comment by 4darsh-Dev** [comment]
@Garima-149 yes 👍🏻 ,
you can refer to var(--color-primary) from CSS variables in style.css

**Comment by 4darsh-Dev** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
