### ISSUE TITLE
Adding chatbot 

### ISSUE THREAD

**Issue by Garima-149** [4darsh-Dev/CogniGaurd#137]
@4darsh-Dev I would like to add chatbot at left-bottom corner.It will help users to ask their queries and will enhance the UI of website. 
Please assign me with  this issue.
![Screenshot (99)](https://github.com/4darsh-Dev/CogniGaurd/assets/143211271/43352510-70bf-4925-b0f6-d9166dc99fac)

**Comment by 4darsh-Dev** [comment]
assigned to @Garima-149 , 
i've already working on a RAG chatbot , you can make the UI for it.

**Comment by Garima-149** [comment]
Ok

**Comment by ruthwikchikoti** [comment]
@Garima-149, may I work on this? eager to contribute.

**Comment by Garima-149** [comment]
@4darsh-Dev ![IMG_20240718_182622.jpg](https://github.com/user-attachments/assets/5577a48b-1244-4888-9799-635fa122b3bb)
I have made UI of chatbot as you instructed. 
Please check, is it fine?

**Comment by 4darsh-Dev** [comment]
@Garima-149  use  a circular container and put this icon inside it. similar to back top top button. 
with icon colour should be white and the container color-primary and 
on hover, the container color changes to black, 

Is it functional? Does a dialog box appear onclick?

for reference, 
link : https://fin-veda.vercel.app/

 ### SS
![Screenshot 2024-07-18 223123](https://github.com/user-attachments/assets/e4ba179f-9201-4452-a8a2-4190f42f0c6c)

**Comment by Garima-149** [comment]
Yes it is functional

**Comment by 4darsh-Dev** [comment]
can you share the SS or video preview?

**Comment by Garima-149** [comment]
@4darsh-Dev ![IMG_20240718_223842.jpg](https://github.com/user-attachments/assets/a01b7fe0-9824-4399-85e3-68bba8470306)

**Comment by 4darsh-Dev** [comment]
good work @Garima-149. 
adjust it's min-height such that it can handle length of the conversations. 

How you're saving the chat message, local storage or any other means ?
In case user closes and reopens it, chat's should be there.

**Comment by Garima-149** [comment]
![IMG_20240718_224808.jpg](https://github.com/user-attachments/assets/af032faf-32fe-41f6-b345-94a7459047ee)

Yes, it will handle the length according to texts. 
I have yet added the UI, not the local storage part. If you say, I will add it too for permanent saving

**Comment by 4darsh-Dev** [comment]
yes, add the storage part, we'll be handling the chat response through API call, 

 chat buttons looks nice, add hover effects to change blue color to black

**Comment by 4darsh-Dev** [comment]
till that create at least one PR, 
creating all pr at once might look spamy

**Comment by Garima-149** [comment]
Ok Yes, I added the hovering effect

**Comment by Garima-149** [comment]
Actually my vs code is saying to disable other files which were working on backend. That's why I am completing all the issues once so , I don't need to open the server again again. It's was Already took time at initial stages.

**Comment by 4darsh-Dev** [comment]
okay @Garima-149 , 
you can try using .gitignore just add the relative path to there it will auto ignore the changes in backend files. 

you can chose either way which works for you.

**Comment by Garima-149** [comment]
@4darsh-Dev localstorage is also done. Should I make pr now?

**Comment by 4darsh-Dev** [comment]
sure @Garima-149

**Comment by 4darsh-Dev** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
