### ISSUE TITLE
Progressbar below navbar

### ISSUE THREAD

**Issue by Garima-149** [4darsh-Dev/CogniGaurd#138]
@4darsh-Dev I would like to add progress bar which will track the loading of webpage.I thought  of placing it  below navbar section.Please assign me with this issue.
![Screenshot (99)](https://github.com/4darsh-Dev/CogniGaurd/assets/143211271/b9ce5e3f-e19c-4000-a7fa-da0ddf44c8e5)

**Comment by 4darsh-Dev** [comment]
assinged to you @Garima-149 , 
complete the work as well, you've been assigned so many issues at once.

**Comment by Garima-149** [comment]
@4darsh-Dev Could you please help me that How to setup this project on my local network? I have tried according to readme. Md file available but It's not clear.

**Comment by 4darsh-Dev** [comment]
okay @Garima-149 :
Here's a simplified version. 
1. You fork the repo and clone it to your device. 
2. navigate to django-web-app ( working directory) where you have to work. 
3. Create a virtual environment(venv)  using python (3.12) (prefer) 
4. activate the venv 
5. Install dependencies using pip 
6. create a .env file in your working directory for managing environment variables. 
7. Just add any value of sample .env file ( to avoid any errors ) of missing values. 
8. Now you have to start a django development server, before that 
9. comment out urlpatterns code as shown in code sample and turn DEBUG=True 
10. python manage.py runserver. 
11. Make changes in respective files. 
12. Undo development changes ( 9 pt)
13. push the code
14.

**Comment by 4darsh-Dev** [comment]
any errors share the SS ?

**Comment by Garima-149** [comment]
Ok Thanku so much

**Comment by Garima-149** [comment]
![Screenshot (104)](https://github.com/user-attachments/assets/c41d9839-e280-48cc-bd58-4059c7877c04)
@4darsh-Dev I am getting this error.What should I do  to solve this?

**Comment by 4darsh-Dev** [comment]
have you added sqlite3 database instead of the vercel production database see reference from readme.

**Comment by 4darsh-Dev** [comment]
@Garima-149 the error message is incomplete share the last few lines.

**Comment by Garima-149** [comment]
![Screenshot (106)](https://github.com/user-attachments/assets/542581b1-2c69-42b9-a40e-b7d59f89d97e)
This is complete error

**Comment by 4darsh-Dev** [comment]
have you created a new file .env in the django-web-app directory with default values?
@Garima-149 
this is due to missing client-id  key

**Comment by 4darsh-Dev** [comment]
create an .env file with 
CLIENT_ID = your-sample-value

**Comment by Garima-149** [comment]
@4darsh-Dev I created  . env file in working directory but showing  same error again.

**Comment by 4darsh-Dev** [comment]
okay got it, 
@Garima-149  have you applied migrations to sqlite3 database, 
python manage.py makemigrations
python manage.py migrate. 

-- this will create all the tables required for project. 
mitigating the error.
-- tell me if you got any other errors.

**Comment by Garima-149** [comment]
@4darsh-Dev I have created all the comments and changes for sql data base  and when I did the command python manage. Py migrations. Then, it showed this error.

**Comment by 4darsh-Dev** [comment]
okay @Garima-149 , 
this error might be due to api/views.py might be calling a function which requires a URL from api_request, but currently due to new database there are no requests already. 
do the best bug hunting comment out a simple code . 
which is calling that api_request, 

urlLen = len(dpUrls)
share ss of api/views.py last few lines of code ... which is calling that function.

**Comment by 4darsh-Dev** [comment]
in the new version released, I've changed this to stop calling automatically.

**Comment by 4darsh-Dev** [comment]
connect me on discord , 
to fix that issue now, 
or gssoc project group on discord..

**Comment by 4darsh-Dev** [comment]
![Screenshot 2024-07-15 110541](https://github.com/user-attachments/assets/6a344b76-e493-4883-bd27-20b6b9288f25)

commenting these lines might fix the error, 

### from 68 to 75

**Comment by Garima-149** [comment]
@4darsh-Dev  The project is working on my local host but I am facing an error that whenever I am changing something in js files in my working directort, it is not reflecting on website. What could be the possibile  issue in that?

**Comment by 4darsh-Dev** [comment]
@Garima-149 , it might be due to browser caches, 
try using ctrl+f5 for reload on PC keyboard, on laptop use this fn lock enabled, 
see if it works,

**Comment by Garima-149** [comment]
Yes changes are not showing on clicking inspect tab.

**Comment by 4darsh-Dev** [comment]
@Garima-149 got the issue, 
use innerHTML, not innerText
```  backToTopButton.innerHTML = '<i class="fa-solid fa-arrow-up"></i>';```
![Screenshot 2024-07-16 131616](https://github.com/user-attachments/assets/c2141139-66ee-4d23-881b-91c2e156324a)

**Comment by 4darsh-Dev** [comment]
Some points. 
1. make changes in terms_of_use.js and privacy_policy.js as well. 
2. while creating PR 👍🏻  commit on changed files only, so no conflicts arise due to changes in settings.py and urls.py

**Comment by Garima-149** [comment]
Ok I will check this but it is not just about html error. I have also tried several other changes in css and other files but they were also not updating on the site. Even not in console.

**Comment by Garima-149** [comment]
![Screenshot (112)](https://github.com/user-attachments/assets/1d0987fd-8e23-4130-9183-667846939e2c)

@4darsh-Dev Please review the progressbar?

**Comment by 4darsh-Dev** [comment]
@Garima-149  make it thinner, 
try with different color options, slightly darker as background is light.

**Comment by Garima-149** [comment]
@4darsh-Dev ![IMG_20240716_233550.jpg](https://github.com/user-attachments/assets/4e6e3ece-d898-43fe-ac7d-81fe38fac97e)

Is it good?

**Comment by 4darsh-Dev** [comment]
@Garima-149 yes, 
much better. 👍🏻

**Comment by 4darsh-Dev** [comment]
Hey @Garima-149 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
