### ISSUE TITLE
Bullet Points in "Dark Patterns"

### ISSUE THREAD

**Issue by AkshitGarg24** [4darsh-Dev/CogniGaurd#139]
Under the dark patterns dropdown menu, along with its contents, bullet points are also being showed which decrease the user interface of the website.

![drop](https://github.com/4darsh-Dev/CogniGaurd/assets/153659573/f378562e-5fa2-44ff-be99-76c364873c90)

**Comment by 4darsh-Dev** [comment]
assigned to you @AkshitGarg24 
go through contributing guidelines and readme for local project setup. 
join discord for mentor support

**Comment by 4darsh-Dev** [comment]
Hey @AkshitGarg24 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
