### ISSUE TITLE
UI of "Types of dark Patterns"

### ISSUE THREAD

**Issue by AkshitGarg24** [4darsh-Dev/CogniGaurd#140]
The design of all cards present "Types of Dark Patterns" should be made same so as to give a consistent look to the users.

![drop](https://github.com/4darsh-Dev/CogniGaurd/assets/153659573/21bc7ca3-83c7-4591-907e-0fb4850aab13)
All cards should be made as what I have attached in the image.

**Comment by 4darsh-Dev** [comment]
assigned to you @AkshitGarg24

**Comment by 4darsh-Dev** [comment]
Hey @AkshitGarg24 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
