### ISSUE TITLE
Making smooth transition on "Back To Top" button

### ISSUE THREAD

**Issue by AkshitGarg24** [4darsh-Dev/CogniGaurd#143]
On clicking the "Back to Top" button, the transition to the page's top should be smooth. I am attaching a video as an example.

https://github.com/4darsh-Dev/CogniGaurd/assets/153659573/58d9ae57-2c4e-4147-a19c-f11cb680f79a

**Comment by 4darsh-Dev** [comment]
assigned to you @AkshitGarg24

**Comment by 4darsh-Dev** [comment]
Hey @AkshitGarg24 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
