### ISSUE TITLE
feat: Modifying The Home Page

### ISSUE THREAD

**Issue by AshmitaBarthwal** [4darsh-Dev/CogniGaurd#149]
I would like to modify the navbar of the website that matches the blue theme of the website also i want to make the homepage attractive by placing the glass blue effect in the front text using css properties.
Sharing the new look of website below.
![Screenshot 2024-07-17 162808](https://github.com/user-attachments/assets/88f20009-9eb3-4ad9-a498-5856687a6aaf)
THESE ARE THE CHANGES I AM PLANNING TO DOT 
@4darsh-Dev Assign this issue to me, also mark the LEVEL of contribution and GSSOC 24 label to my issue.

**Comment by AshmitaBarthwal** [comment]
@4darsh-Dev assign this issue to me under Gssoc.

**Comment by AshmitaBarthwal** [comment]
@4darsh-Dev this comes under enhancement label.
Don't know why bug label has been assigned.

**Comment by 4darsh-Dev** [comment]
okay @AshmitaBarthwal , 
but you need to work on the design, 
propose a better design,

**Comment by 4darsh-Dev** [comment]
Hey @AshmitaBarthwal ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
