### ISSUE TITLE
➕Enhancement: Improving the "FAQ Section" of the Website🌟

### ISSUE THREAD

**Issue by Tejashri-Taral** [4darsh-Dev/CogniGaurd#150]
Hey @4darsh-Dev  ,

I would like to enhance the UI and functionality of the current FAQ page to improve user experience.

**Here's what I Will do:**
- Add collapsible sections for questions to streamline navigation and reduce clutter.
- Update existing content and add new comprehensive questions based on user feedback and common inquiries.
- Styling it to follow the Website's theme.
- Adding transition moving effect to the FAQ sections questions.

****For example like this-****

![image](https://github.com/user-attachments/assets/dae8ec44-f18c-4b22-9057-2467665fd86c)

**Are you contributing under any open-source program?**
GSSOC'24

I hope I was able to explain the issue and the expected solution.
If so, Could you please assign this issue to me under GSSoC 24?

**Comment by 4darsh-Dev** [comment]
okay @Tejashri-Taral , 
Go through readme.md and contributing.md for local project setup guidelines.

**Comment by 4darsh-Dev** [comment]
Hey @Tejashri-Taral ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
