### ISSUE TITLE
Add Dark and Light mode theme option.

### ISSUE THREAD

**Issue by kou95shik** [4darsh-Dev/CogniGaurd#155]
I will add the feature that can switch dark mode to light mode and vice versa.

**Comment by 4darsh-Dev** [comment]
@kou95shik  assigned to you,
Please check the contributing guidelines and see local project setup steps in readme and pinned issues as notice,
Join our gssoc project discord for mentor guidance.

**Comment by 4darsh-Dev** [comment]
any update @kou95shik ?

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for Closing of Contribution period for GSSoC 24'
 Finish your work and raise the PRs ASAP to get your points. 
 Thanks💗 for your valuable Contributions!

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials

**Comment by 4darsh-Dev** [comment]
Hey @kou95shik ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
