### ISSUE TITLE
Types of Dark pattern page content out of screen 

### ISSUE THREAD

**Issue by Utsavladia** [4darsh-Dev/CogniGaurd#160]
**Is your feature request related to a problem? Please describe.**
The page needed to be fixed to have a good user experience

![image](https://github.com/user-attachments/assets/39788d2f-251e-4af6-9b72-be46c3ef19bb)

I would love to make it look goood

**Comment by 4darsh-Dev** [comment]
assigned to you @Utsavladia

**Comment by 4darsh-Dev** [comment]
Hey @Utsavladia ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
