### ISSUE TITLE
Auto open FAQ answer on hover 

### ISSUE THREAD

**Issue by Utsavladia** [4darsh-Dev/CogniGaurd#161]
**Is your feature request related to a problem? Please describe.**
The FAQ question should auto open the answer for that question on hovring on it 

![image](https://github.com/user-attachments/assets/0bda0e88-18df-4e3d-a19b-0649026606fe)

this will enhance the user experience of using the website 
I would love to contribute to this under GSSOC

**Comment by 4darsh-Dev** [comment]
assigned to you @Utsavladia

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
