### ISSUE TITLE
NOT GOOD FAQ section for mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [4darsh-Dev/CogniGaurd#162]
**Is your feature request related to a problem? Please describe.**
It should be fixed to have a good view on the mobile screen also 

![image](https://github.com/user-attachments/assets/9072230c-9d48-40b1-9672-eba9411c1ed8)

I would love to fix and make it look uniform for better user experience

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for Closing of Contribution period for GSSoC 24'
 Finish your work and raise the PRs ASAP to get your points. 
 Thanks💗 for your valuable Contributions!

**Comment by Utsavladia** [comment]
@4darsh-Dev 
Kindly mrege this PR before GSSOC ends 😌

**Comment by 4darsh-Dev** [comment]
Hey @Utsavladia ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
