### ISSUE TITLE
Home page content overlaps on Mobile screen 

### ISSUE THREAD

**Issue by Utsavladia** [4darsh-Dev/CogniGaurd#163]
**Is your feature request related to a problem? Please describe.**
It should be fixed to have a better user experirnce on all devices

![image](https://github.com/user-attachments/assets/014e4e23-e983-4daf-be97-cf41900d0dd4)

I would love to fix it under GSSOC and  make the user experience better

**Comment by 4darsh-Dev** [comment]
what screen dimensions are you using ? 
@Utsavladia

**Comment by 4darsh-Dev** [comment]
Hey @Utsavladia ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
