### ISSUE TITLE
Footer content not aligned properly on mobile screen 

### ISSUE THREAD

**Issue by Utsavladia** [4darsh-Dev/CogniGaurd#164]
**Is your feature request related to a problem? Please describe.**
It should have a uniform look to make it llook better

![image](https://github.com/user-attachments/assets/a50fb8cd-e91f-4afe-995e-e8b65258dda1)

I would love to contribute to this and make the user experience better for the users

**Comment by 4darsh-Dev** [comment]
assigned to you @Utsavladia  go through conributing guidelines and readme for project setup. 
let's me know if you face any issues.

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
