### ISSUE TITLE
dark mode pattern nav

### ISSUE THREAD

**Issue by Sandeepkumargond** [4darsh-Dev/CogniGaurd#171]
**Describe the bug**
the dark mode pattern nav key has two drop down 
**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2024-08-06 093123](https://github.com/user-attachments/assets/3df86642-503c-4cb1-a470-78f70d2f6532)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 4darsh-Dev** [comment]
assigned to you @Sandeepkumargond , 
Go through contributing guidelines and readme for local project setup. 
Add a preview SS or video of your desired change.

**Comment by riteshjha61253** [comment]
@4darsh-Dev I want to work on this issue please assign this issue to me

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for Closing of Contribution period for GSSoC 24'
 Finish your work and raise the PRs ASAP to get your points. 
 Thanks💗 for your valuable Contributions!

**Comment by 4darsh-Dev** [comment]
Hey @Sandeepkumargond ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
