### ISSUE TITLE
Adding Dynamic Scroll Indicator 

### ISSUE THREAD

**Issue by Sourabh782** [4darsh-Dev/CogniGaurd#173]
**Is your feature request related to a problem? Please describe.**
When scrolling through the website, i want to add a scroll indicator, which moves as we scroll through the site. It helps user experience and adds interactivity to the site

**Describe the solution you'd like**
i Wanted to implement dynamic scroll indicator at the top of page.  As Some pages in website includes scrolling, it will improve user Experience

![Screenshot 2024-08-09 140049](https://github.com/user-attachments/assets/76ed1af9-86cf-444d-b58a-7fa7052831bc)

**Additional context**

**Comment by 4darsh-Dev** [comment]
assigned to you @Sourabh782,
do raise pr soon

**Comment by Sourabh782** [comment]
@4darsh-Dev  whats deadline for pr??

**Comment by Sourabh782** [comment]
ill try my best to complete this before 2-3pm

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for Closing of Contribution period for GSSoC 24'
 Finish your work and raise the PRs ASAP to get your points. 
 Thanks💗 for your valuable Contributions!

**Comment by Sourabh782** [comment]
Hi, @4darsh-Dev, i have having a bit trouble setting up the project can you help?

**Comment by 4darsh-Dev** [comment]
sure, share the preview SS of the error. 
@Sourabh782

**Comment by Sourabh782** [comment]
Actually i followes all steps given in readme.md for website
![image](https://github.com/user-attachments/assets/4f505edf-7036-4cf7-a47c-e8a5ca175ac9)

**Comment by Sourabh782** [comment]
means i know what all cahnges i have to do in indec .html file, but cant run it on browser

**Comment by Sourabh782** [comment]
@4darsh-Dev sir, i executed the html css files to develop scroll indicator, 
i was having problem in running django server, so i implemented feature directly by working on html css js part of project, 

https://github.com/user-attachments/assets/b354a65b-cb13-4de5-a8a2-91d7ffc7f1ab

i have not implemented all css files so the site looks a disorted, but the feature implementation is working as expected.

**Comment by 4darsh-Dev** [comment]
okay @Sourabh782 , 
instead of adding on top, can you update the bottom one it's will be much better. 
Raise the PR with only committing the HTML,CSS and js file 
do it asap

**Comment by Sourabh782** [comment]
sure sir

**Comment by Sourabh782** [comment]
@4darsh-Dev sir made PR req

**Comment by 4darsh-Dev** [comment]
Hey @Sourabh782 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
