### ISSUE TITLE
Extra DropDown Indicator in NavBar

### ISSUE THREAD

**Issue by Sourabh782** [4darsh-Dev/CogniGaurd#174]
**Describe the bug**
There is an extra dropdown indicator at NavBar

![ss](https://github.com/user-attachments/assets/29e476ef-af72-46dd-bbac-9573b33d558d)

**To Reproduce**
1. Open site, you can see it in navbar
2. See error

**Expected behavior**
There should be only one dropdown icon

**Screenshots**
![ss](https://github.com/user-attachments/assets/e12db8b9-bde8-47df-b9fa-3dbad2afd5b5)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  -- windows
 - Browser [e.g. chrome, safari]  -- chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 4darsh-Dev** [comment]
its fixed already

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for Closing of Contribution period for GSSoC 24'
 Finish your work and raise the PRs ASAP to get your points. 
 Thanks💗 for your valuable Contributions!

**Comment by 4darsh-Dev** [comment]
Hey @Sourabh782 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇

**Comment by 4darsh-Dev** [comment]
GSSoC 24 has been completed Finally'
 It was a great experience working with you all 
 Thanks💗 for your valuable contributions! 
 PA nomination has been started, Do fill out the forms soon. Share your experiences and let's connect on socials
