### ISSUE TITLE
[URGENT] Make Web pages responsive across android and i pad devices

### ISSUE THREAD

**Issue by 4darsh-Dev** [4darsh-Dev/CogniGaurd#21]
## Changes to be made: 
1. Add hamburger menu button for android device and  a beautiful navbar.
2. properly size boxes and font size for small devices.
3. update footer and narbar ( better appearence)
4. Make the contact form responsive

**Comment by kusumdesai** [comment]
Hey @4darsh-Dev !!! 
Can you please assign this issue to me under GSS0C?

**Comment by 4darsh-Dev** [comment]
@kusumdesai sorry for the delay but our project got registered with gssoc yesterday, 
so you can now work on this issue .
keep updating your progress and issues

**Comment by Komalpreet-Kaur112** [comment]
Hey @4darsh-Dev 
I too want to work on this issue. Please assign it to me.

**Comment by 4darsh-Dev** [comment]
@Komalpreet-Kaur112 , under gssoc assignment is on first come first serve basis, 
so I can assign it to you if she has not responded  over 5+days, 
Or if you want to collaborate with him, talk to him and divide the work. 
I will assign it to both of you.

**Comment by 4darsh-Dev** [comment]
@kusumdesai  any work update ?

**Comment by 4darsh-Dev** [comment]
@Komalpreet-Kaur112  do you still want to work on it ?

**Comment by Komalpreet-Kaur112** [comment]
@4darsh-Dev 
Yes, I do want to work on this issue but will need some guidance as this will be my first contribution on this platform.

**Comment by 4darsh-Dev** [comment]
okay @Komalpreet-Kaur112, 
But first let me know are you familiar with html, css and js ?
especially css media queries and all to make it responsive and user friendly.

**Comment by Komalpreet-Kaur112** [comment]
@4darsh-Dev 
Yes, I have worked in these all.

**Comment by 4darsh-Dev** [comment]
okay assigned to you @Komalpreet-Kaur112

**Comment by Komalpreet-Kaur112** [comment]
@4darsh-Dev 
Thank you for assigning me this task.
I have started working on it.

**Comment by Komalpreet-Kaur112** [comment]
Hey @4darsh-Dev 
I am unable to get those changes (django-web-app) on my system. I have tried fetching origin several times but still it hasn't worked to get those changes.
So, I tried working on the previous code. But I had some doubts regarding mobile phone responsiveness . So can you please provide me with the exact breakpoints for setting up the mobile responsive design ?

**Comment by sanskritisahu21** [comment]
I would like to contribute on this issue under Gssoc'24. Please assign me the issue.

**Comment by 4darsh-Dev** [comment]
@Komalpreet-Kaur112  you have to use css media queries , you can choose breakpoints 
1. max-width ( 480 to 320)
2. 480 - 900
3. 900 - 1300
4. 1300 - 1980 ..
acutally you need breakpoints for mobile device range, i pad ios devices and , laptops screens

**Comment by 4darsh-Dev** [comment]
@Komalpreet-Kaur112  any work update?

**Comment by Komalpreet-Kaur112** [comment]
Hey @4darsh-Dev 
Thank you for sharing the details about the breakpoints.
I have created a hamburger menu, just a few settings left and about to finish responsiveness across ipad.
Currently, I have my exams going on until next week which is why I don't get enough time to work on the project. But I ensure you to get it all done sooner after my exams.

**Comment by Komalpreet-Kaur112** [comment]
> @Komalpreet-Kaur112 i've updated the frontend code in a separate project with folder named django-web-app, which is also live make your changes in that. If you've found any issues settting up project locally tell me.
Please help me know where to start from now as there are so many files in django-web-app. Maybe the base.html is file to start with but there is no css file actually connected to these(not working).
<img width="1273" alt="Screenshot 2024-06-10 at 2 46 27 PM" src="https://github.com/4darsh-Dev/CogniGaurd/assets/143227316/c7c7f648-0109-4f99-9824-ddff3a81cb1a">

Please share these details ,so that I can get it done sooner.

**Comment by 4darsh-Dev** [comment]
you've not setup the project correctly, take reference from the readme, or follow tutorials to setup a django project

**Comment by anurag6569201** [comment]
@4darsh-Dev  assign me i will create whole responsive everypages

**Comment by 4darsh-Dev** [comment]
assigned to you @anurag6569201 , 
check notice pinned in issues and readme for setting project on local device. 
do it soon, others also working on this .

**Comment by anurag6569201** [comment]
@4darsh-Dev can you do it for level 3 !!

**Comment by 4darsh-Dev** [comment]
@anurag6569201 make the changes, if it seems that it require level up then I will add level3 .

**Comment by 4darsh-Dev** [comment]
Hey @4darsh-Dev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
