### ISSUE TITLE
Update and enhance the Documentation.txt file

### ISSUE THREAD

**Issue by abhi-la-sha** [4darsh-Dev/CogniGaurd#22]
The look of the Documentation file is not right.
I can make the file look better by fixing the Font size, headings, indentation, etc. It'll be easily readable for everyone.

@4darsh-Dev Kindly label the issue and assign it to me.

![WhatsApp Image 2024-05-27 at 12 42 31_ce66ee2a](https://github.com/4darsh-Dev/CogniGaurd/assets/154429742/1c51e372-1db5-403b-bda2-21d68edec143)

**Comment by 4darsh-Dev** [comment]
@abhi-la-sha  thanks for showing interest, 
but we have moved our docs to wiki page and readme itself, so it is no longer needed.
You can find more things to contribute in project as well.
