### ISSUE TITLE
Issue with vercel.json python runtime deployment

### ISSUE THREAD

**Issue by 4darsh-Dev** [4darsh-Dev/CogniGaurd#24]
## Description
The project was build with python 3.11.5 so requirements.txt contains all the libraries accordingly,
But vercel is using python 3.12 which is creating issues and results in deployment failure.

### Need to fix it,
already tried setting runtime 3.11.5 in vercel.json but it didn't work

**Comment by aryansharma220** [comment]
@4darsh-Dev We can update the dependencies in the code if it doesn't break anything. Or we can explicitly specify the python version in the requirements.

**Comment by 4darsh-Dev** [comment]
okay , try it and see if it works or not .

**Comment by 4darsh-Dev** [comment]
fixed
