### ISSUE TITLE
credentials in web extension are hard coded which raise security issue

### ISSUE THREAD

**Issue by 4darsh-Dev** [4darsh-Dev/CogniGaurd#25]
## Description
Currently in web extension credentials of username and password for authentication from django api (rest framework) is hard coded
find ways to fix that security issue.
While sending post request it is converted to base64.

### Propose changes and how it can be solved

**Comment by scientest** [comment]
you remove the need for hard-coded credentials and increase security. The process involves setting up Django REST Framework with JWT, handling tokens in the web extension, and ensuring secure API requests. This approach not only secures the authentication mechanism but also aligns with best practices for modern web applications.

**Comment by 4darsh-Dev** [comment]
okay, 
It sounds great so first we need to setup user Authentication on our web app from where user can obtain access and refresh token with their credentials , which can work further and stored in chrome storage.
We can also limit the usage of token requests for users.

**Comment by 4darsh-Dev** [comment]
Hey @4darsh-Dev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
