### ISSUE TITLE
Spelling errors 

### ISSUE THREAD

**Issue by debangi29** [4darsh-Dev/CogniGaurd#27]
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/117537653/799c567c-ac3b-4962-af6c-a8d2d797b5ad)

Browser spelling wrong.

**Comment by debangi29** [comment]
Please assign me the issue @4darsh-Dev

**Comment by 4darsh-Dev** [comment]
@debangi29 I can assign this to you but please find meaningful contributions, 
it can't be grouped inside any levels

**Comment by debangi29** [comment]
Okayy, thank youuu...!!
