### ISSUE TITLE
Feature Request: Add Theme Toggle Button to Navbar

### ISSUE THREAD

**Issue by AnkitLuhar** [4darsh-Dev/CogniGaurd#29]
**Description:
Problem: Bright interfaces strain users' eyes, especially in low-light conditions, lacking customization options.

Solution: Introduce a theme toggle button (black/dark blue) on the navbar for easy switching, enhancing user comfort and usability.

Benefits:

1>Reduced eye strain.

2>Enhanced customization.

3>Improved accessibility.

4>Modern aesthetics.

Labels: Feature Request, UI/UX, Customization,gssoc**

Attachments: 

![Screenshot (465)](https://github.com/4darsh-Dev/CogniGaurd/assets/142730608/f7b12059-2052-46c6-b223-8257c9aa8def)

Assign me under Gssoc24.

**Comment by AnkitLuhar** [comment]
This feature request is assigned under GSoc24. Awaiting your feedback to commence work promptly.

**Comment by 4darsh-Dev** [comment]
@AnkitLuhar  the SS you have attached is of streamlit web app which is deployed on the huggingface hub spaces for demonstration purpose only,
If you want to add theme toggle feature, updated in the django web app , which has multiple pages, 
and it will be used for user authentication for web extension. 
## SS
![Screenshot 2024-05-30 220754](https://github.com/4darsh-Dev/CogniGaurd/assets/109789509/3380017d-48cb-47af-b0a3-8b165224936c)

### If you are ready to work on it. I can assign you this under gssoc

**Comment by AnkitLuhar** [comment]
@4darsh-Dev  sure , i will work on it  & soon update you about the work....

**Comment by 4darsh-Dev** [comment]
any update @AnkitLuhar  ?

**Comment by AnkitLuhar** [comment]
@4darsh-Dev Thanks for waiting. There is an issue with my laptop; it has a hardware problem. It might take 2-3 days to fix. I will complete it and raise the pull request as soon as possible.

**Comment by AnkitLuhar** [comment]
@4darsh-Dev, I've been working on the project for the past 2 to 3 hours, but there has been a continuous issue arising with the backend server. Additionally, my Windows Defender has detected some type of virus. Unfortunately, I have to close this issue. I apologize for any inconvenience and I'm happy to contribute to your other project, especially if it's web-based. Just let me know.

**Comment by 4darsh-Dev** [comment]
okay
