### ISSUE TITLE
improve footer 

### ISSUE THREAD

**Issue by aashkaaaaaa** [4darsh-Dev/CogniGaurd#32]
can improve the footer and add the social media icons with hover.
could you assign me this issue under GSSoC'24.

**Comment by 4darsh-Dev** [comment]
@aashkaaaaaa  have you tested project locally, 
our django web app already contains footer and social icons, 
explain about changes you want in footer with details and SS of designs for better clarity.

**Comment by aashkaaaaaa** [comment]
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/138461600/fd6a45df-5dc9-4ece-97a8-f0082d8d6ba7)
there i want to improve

**Comment by 4darsh-Dev** [comment]
it can't be grouped as levels @aashkaaaaaa under gssoc,
if u want i can add gssoc tag,
