### ISSUE TITLE
adding dark mode

### ISSUE THREAD

**Issue by dnyandeepchute** [4darsh-Dev/CogniGaurd#39]
there will be a field(symbol) on right top corner for changing the mode of web to dark and again back to normal.

useful for the user as it help the user to use it and see content in better way and also useful for website as it gives a different look and experience.

using dark mode help user to-
Reduces eye strain
Gives a productivity boost
Saves battery life

**Comment by dnyandeepchute** [comment]
please assign this to me

**Comment by Gultreen** [comment]
Dark Mode: Optional dark mode for better usability in low-light environments. 
It makes a better look for the website also.
I am GSSoC Contributor .
kindly @4darsh-Dev ,assign me this task to start work on it

**Comment by 4darsh-Dev** [comment]
this issue has already assigned , in a previous issue which is similar to this.
