### ISSUE TITLE
updating the nav bar

### ISSUE THREAD

**Issue by dnyandeepchute** [4darsh-Dev/CogniGaurd#40]
there is no change on hover for element/pages/links present in nav bar. it is not look good and even creating problem for users.

**Comment by dnyandeepchute** [comment]
please assign this to me

**Comment by 4darsh-Dev** [comment]
okay, assigned to you @dnyandeepchute ,
but share screenshot or design of changes you want to make, 
add icons right next to home, about ... to make it look attractive.
you can also propose good logo if you want .

**Comment by dnyandeepchute** [comment]
![Screenshot 2024-06-05 122008](https://github.com/4darsh-Dev/CogniGaurd/assets/158272735/6116d0cd-f2ca-4fcd-8a89-3593c3bf5501)

done @4darsh-Dev 
please accept PR, thank you
