### ISSUE TITLE
updating the footer

### ISSUE THREAD

**Issue by dnyandeepchute** [4darsh-Dev/CogniGaurd#41]
![Screenshot 2024-06-04 175812](https://github.com/4darsh-Dev/CogniGaurd/assets/158272735/4cf6145f-00ad-42ab-b415-63171ad4a118)

there is no change on hover for all the page links, social media icons present at footer and even no proper spacing and size of feedback and subscribe button.

**Comment by dnyandeepchute** [comment]
please assign this to me

**Comment by 4darsh-Dev** [comment]
these are very small changes can't be grouped under levels, 
i can still assign you it under gssoc

**Comment by dnyandeepchute** [comment]
thank you @4darsh-Dev , but it will be great if you add a level to.

**Comment by 4darsh-Dev** [comment]
you need to make more changes rather than just adding hover effect and size changes

**Comment by dnyandeepchute** [comment]
yes i will do that.

**Comment by 4darsh-Dev** [comment]
Hey @dnyandeepchute ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
