### ISSUE TITLE
[Feature] Propose a better UI/UX design for the web pages 

### ISSUE THREAD

**Issue by 4darsh-Dev** [4darsh-Dev/CogniGaurd#43]
### Changes to be made
1. Propose a new UI/UX design for the web pages using figma , canva or similar tools
2. Choose properly responsive font-size and color-palettes 
3. Icons and images, vectors wherever needed.
4. CSS Animations and effects to make it more attractive.
5. Design for home,about,report ... and other pages 

### Screenshots 
visit the live link : https://cogni-gaurd.vercel.app

**Comment by dnyandeepchute** [comment]
@4darsh-Dev please assign this to me, thank you.

**Comment by 4darsh-Dev** [comment]
Issue will be assigned after seeing the proposal, so everyone who want to contribute to this issue, 
first share a sample of what i mentioned in changes.

**Comment by Dharmi-dev** [comment]
@4darsh-Dev  I would like to work on this -- you can see my FIGMA profile 
https://www.figma.com/files/recents-and-sharing/recently-viewed?fuid=1291421611710708732

I am a UI/UX enthusiast and very excited to work on this project. Hope you would assign this task to me

**Comment by 4darsh-Dev** [comment]
I am not asking for profile, propose the design which you will be implementing, with font and color combinations for the pages

**Comment by 4darsh-Dev** [comment]
@Dharmi-dev  link  is asking to log in

**Comment by 4darsh-Dev** [comment]
anyone interested ?

**Comment by Amishachoudhary22** [comment]
Yeah I am Interested. I will propose my designs by today.

**Comment by Amishachoudhary22** [comment]
https://www.figma.com/design/NLPQPOvUwL3ALYHeEefKKl/Untitled?node-id=0-1&t=vicfwixbsXqeWxXT-1
The above is the Figma link for the design.
<img width="857" alt="Screenshot 2024-06-11 at 12 03 12 PM" src="https://github.com/4darsh-Dev/CogniGaurd/assets/103454929/1070e10a-2e6f-46e5-8d42-980e749c4582">
<img width="865" alt="Screenshot 2024-06-11 at 12 03 19 PM" src="https://github.com/4darsh-Dev/CogniGaurd/assets/103454929/f769107a-94a1-40c4-be9e-cf2ce0f73afc">
<img width="876" alt="Screenshot 2024-06-11 at 12 03 29 PM" src="https://github.com/4darsh-Dev/CogniGaurd/assets/103454929/7446eba6-8773-4bce-9dd7-50303c854261">
<img width="864" alt="Screenshot 2024-06-11 at 12 03 35 PM" src="https://github.com/4darsh-Dev/CogniGaurd/assets/103454929/b3cc3ebb-0b7c-4d5f-9097-19a48de8253f">

**Comment by 4darsh-Dev** [comment]
@Amishachoudhary22  not that impressive and good looking, 
try taking reference from already existing designs on web. 
and popular animations and effects. 
it seems very basic .
