### ISSUE TITLE
Include feedback form

### ISSUE THREAD

**Issue by ananyag309** [4darsh-Dev/CogniGaurd#46]
Would like to design a simple feedback form with a similar color interface as the website. @4darsh-Dev sir, please assign this issue to me under gssoc.

also, you would like to have a different page for feedback or just a pop up form

**Comment by 4darsh-Dev** [comment]
okay @ananyag309, you can work on feedback form under a new page "contact", and add other contact images, icons and links to make it attractive as well.
are you familiar with django ?

**Comment by ananyag309** [comment]
I am not familiar with django yet.

**Comment by ananyag309** [comment]
@4darsh-Dev sir if this could work?? this is just draft i will edit it more. 
![this](https://github.com/4darsh-Dev/CogniGaurd/assets/145869907/24749eff-8dc5-4a7a-8894-1ec316ecf26f)

**Comment by 4darsh-Dev** [comment]
@ananyag309  good work, 
it looks fine but need some tweaking,  for a contact page try to find suitable image , 
u can choose vectors from https://www.freepik.com/
for design refer - > https://dribbble.com/tags/contact-page

**Comment by 4darsh-Dev** [comment]
@ananyag309 just you have understand jinga syntax in django, easy
means most code will remain same, but format will change a bit , 
read the code for other pages, and tell me if you have any doubts ?

**Comment by ananyag309** [comment]
@4darsh-Dev I have started with django, i will definately go by jinga syntax and will be sending a much more better contact page soon.

**Comment by 4darsh-Dev** [comment]
@ananyag309 any work update?
join our project discord

**Comment by ananyag309** [comment]
sorry sir for late i will do final submission by 10 july as my sem exam started ending on 6 july

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for Closing of Contribution period for GSSoC 24'
 Finish your work and raise the PRs ASAP to get your points. 
 Thanks💗 for your valuable Contributions!

**Comment by 4darsh-Dev** [comment]
Hey @ananyag309 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
