### ISSUE TITLE
Feat: Font Change

### ISSUE THREAD

**Issue by chaanakyaaM** [4darsh-Dev/CogniGaurd#54]
The font of the 'Get started' and 'Give feedback' is different from the whole website, which makes the website a bit odd.

![image](https://github.com/4darsh-Dev/CogniGaurd/assets/131477601/b74a0498-3860-4b2c-99e0-d41db94c0c0a)

I would like to change the font of these button on the homepage.

**Comment by 4darsh-Dev** [comment]
@chaanakyaaM  assigned to you, 
but this is very small change, you can get only 1 point, 
cannot be grouped as levels.

**Comment by chaanakyaaM** [comment]
ok
