### ISSUE TITLE
want to add hover to social media icons

### ISSUE THREAD

**Issue by Shreyaa173** [4darsh-Dev/CogniGaurd#57]
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/144673309/9a1f8b44-f1b2-41e9-8dc5-272855e64ab8)
 please assign me

**Comment by 4darsh-Dev** [comment]
@Shreyaa173 , if you want to make any contribution that counts under level1, 2 or 3 
instead of raising similar issue many times, 
first create a proposal of all changes , that will fix some bug, for ui/ux , 
then you can work on that thing.
