### ISSUE TITLE
want to change documentation 

### ISSUE THREAD

**Issue by Shreyaa173** [4darsh-Dev/CogniGaurd#59]
want to give better documentation
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/144673309/d6553ea9-c104-4b29-ae33-29a93a475730)
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/144673309/3e90a692-6155-4664-91f5-9181e98771da)

**Comment by GAGGZ1** [comment]
@4darsh-Dev PLEASE ASSIGN ME THIS ISSUE

**Comment by Shreyaa173** [comment]
It will look something like this
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/144673309/f30098f9-7989-4414-bfd0-0d788db666f0)

**Comment by 4darsh-Dev** [comment]
good @Shreyaa173 , 
try to find icons, suitable to these dark patterns , you can search them on google. 
take reference from this -> https://www.deceptive.design/

**Comment by 4darsh-Dev** [comment]
Hey @Shreyaa173 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
