### ISSUE TITLE
[Logo] Propose a good logo design for CogniGuard

### ISSUE THREAD

**Issue by 4darsh-Dev** [4darsh-Dev/CogniGaurd#60]
### Make a good logo which is visually appealing 
1. you can use tools like canva, adobe logo maker, looka , and many more ...
2. free to use ai tools (image generations)
3. Don't use copyrighted things without permissions

### Best Design will get the points.

**Comment by Shreyaa173** [comment]
The logos can be like
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/144673309/4c9537eb-4bd5-4e91-b902-c86530a4e767)

![image](https://github.com/4darsh-Dev/CogniGaurd/assets/144673309/58090275-f67e-40fd-86fc-cd0011fc83b5)

![image](https://github.com/4darsh-Dev/CogniGaurd/assets/144673309/fb42bdcb-8adf-4bb1-8c93-ab71361c542d)

![image](https://github.com/4darsh-Dev/CogniGaurd/assets/144673309/c40893e4-2afe-49f2-87a7-1f0c952b117e)

**Comment by Dharmi-dev** [comment]
Hello @4darsh-Dev  I am very thrilled to work for you on this issue of designing a logo 
here is what I made, but can be edited accordingly, I made it on figma
![CogniGuard logo new](https://github.com/4darsh-Dev/CogniGaurd/assets/148576891/63fd4713-03fc-4d58-b541-8385c2a18158)
 
Please, let me work on this issue.

**Comment by 4darsh-Dev** [comment]
Good work @Shreyaa173 , @Dharmi-dev 
@Dharmi-dev  assigned to you. logo is unique and genuine

**Comment by 4darsh-Dev** [comment]
work udpate? @Dharmi-dev

**Comment by 4darsh-Dev** [comment]
Hey @4darsh-Dev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
