### ISSUE TITLE
adding hover effect to links in footer

### ISSUE THREAD

**Issue by dnyandeepchute** [4darsh-Dev/CogniGaurd#63]
adding hover effect to links in footer

**Comment by dnyandeepchute** [comment]
please assign this to me.

**Comment by 4darsh-Dev** [comment]
Hey @dnyandeepchute ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
