### ISSUE TITLE
Adding user experience section on home page

### ISSUE THREAD

**Issue by Shreyaa173** [4darsh-Dev/CogniGaurd#65]
I want to add users experience page for good engagement, enhanced user satisfaction and for building trust and credibility.

**Comment by kashi-verma** [comment]
pls assign me this issue @4darsh-Dev

**Comment by 4darsh-Dev** [comment]
@Shreyaa173 , @kashi-verma 
You can add a testimonials section on the landing page itself, a separate page is not required 
propose the design for the section.
Best proposal will get the points. I'll assign levels after looking into amount of contribution. 
so give you best to get max points.
take inspiration from there - > https://dribbble.com/tags/testimonials

**Comment by thecloudcode** [comment]
Hi @4darsh-Dev , I would like to take up this issue

I have designed a testimonials section for your website at the bottom of the landing page, something like this

![image](https://github.com/4darsh-Dev/CogniGaurd/assets/114615639/61e363a0-2d3d-42d8-b966-0a0f018ad0e6)


Kindly **assign** me the issue, so that I can start working on it.

**Comment by kashi-verma** [comment]
Thanks for assigning this issue to me

**Comment by 4darsh-Dev** [comment]
@thecloudcode  looking great, 
ensure they must be responsive across small screen devices as well, and follow code norms.
and use color and font palletes from style.css 
use properly sized and compressed images (webp format) to avoid vercel deployment issue,

**Comment by 4darsh-Dev** [comment]
@kashi-verma  propose the design first, 
i've not assigned anyone till now .

**Comment by thecloudcode** [comment]
thank you sir for assigning me

**Comment by 4darsh-Dev** [comment]
@thecloudcode any work udpate?

**Comment by thecloudcode** [comment]
Yes sir, by tonight I will be sending a PR

**Comment by 4darsh-Dev** [comment]
@anyone interested ?

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
@Shreyaa173 assigned to you,

**Comment by kashi-verma** [comment]
Thanks for assigning this

**Comment by 4darsh-Dev** [comment]
Hey @Shreyaa173 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
