### ISSUE TITLE
Issue: "Know More" Button for "What are Dark Patterns" Leads to Home Page

### ISSUE THREAD

**Issue by Amishachoudhary22** [4darsh-Dev/CogniGaurd#66]
The "Know More" button under the "What are Dark Patterns" section currently redirects users to the home page. Instead, it should lead to a dedicated page with more detailed information about dark patterns.

Steps to Reproduce

Navigate to the home page.
Scroll down to the "What are Dark Patterns" section.
Click on the "Know More" button.
Expected Behavior

The "Know More" button should redirect to a page that provides comprehensive information about dark patterns.

Actual Behavior

The "Know More" button redirects to the home page.
suggested solution.
Create a new page (e.g., /dark-patterns) with detailed information about dark patterns.
Update the link for the "Know More" button to point to the new page.
here as a page such that already exists in the what are dark pattern section. just the Lin can be updated.

<img width="1048" alt="Screenshot 2024-06-08 at 2 24 15 PM" src="https://github.com/4darsh-Dev/CogniGaurd/assets/103454929/35a000db-27ab-48c6-8a79-0b0be35792f4">

**Comment by 4darsh-Dev** [comment]
yes, you can create a new page, 
for this , propose the design you will be implementing first and use suitable images and vectors, make it look attractive,
i'll add level after looking into how much value it adds to the project.

**Comment by 4darsh-Dev** [comment]
@Amishachoudhary22 any update?

**Comment by Amishachoudhary22** [comment]
I am working on it. will propose a design  by tonight.

**Comment by Amishachoudhary22** [comment]
https://www.figma.com/design/NLPQPOvUwL3ALYHeEefKKl/Untitled?node-id=0-1&t=VKwActjgrvFlhamq-1
above is the link for the file.

**Comment by 4darsh-Dev** [comment]
@Amishachoudhary22 great design for what are dark patterns page
Raise the PR with changing only content, footer and other parts remain same.

**Comment by Amishachoudhary22** [comment]
> @Amishachoudhary22 great design for what are dark patterns page Raise the PR with changing only content, footer and other parts remain same.

Footer remains the same as in same as the home page of cogniguard? Can u please explain the exact changes I need to perform!!

**Comment by 4darsh-Dev** [comment]
yes footer and sidebar remains same as home page, change the remaining content as per your design 

1. start from what are dark patterns till enforcement penalties. 
2. The box containing what are dark patterns is making the text unclear, just remove it
3. blue background with h1 what are dark patterns? add opacity and other effects to make it readable 

## SS
![Screenshot 2024-06-23 135616](https://github.com/4darsh-Dev/CogniGaurd/assets/109789509/23012f90-7acb-4efd-9160-924a2db2e6ab)

**Comment by Amishachoudhary22** [comment]
Okk sure

**Comment by 4darsh-Dev** [comment]
@Amishachoudhary22  I've added a sample page, take reference from that.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by Amishachoudhary22** [comment]
Can u please send the discord link.

**Comment by 4darsh-Dev** [comment]
@Amishachoudhary22  I don't have permission, you've to follow the procedure.

**Comment by 4darsh-Dev** [comment]
Hey @Amishachoudhary22 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
