### ISSUE TITLE
Improve the UI/Ux of the page 

### ISSUE THREAD

**Issue by Amishachoudhary22** [4darsh-Dev/CogniGaurd#67]
I have designed a new UI for Cogniguard to improve user experience and visual appeal. The new design includes updated layout, colors, typography, and interactive elements to enhance functionality and aesthetics.
Observations
I have also noticed that the logo has a misspelling for "Cogniguard." If you suggest, I can redesign the logo to correct this and align it with the new UI design.

Proposal
Here is the UI design I propose. I have tried to keep the elements and the content the same, making changes only to the layout. However, I can propose more design variations if requested.

Attachments
<img width="393" alt="Screenshot 2024-06-08 at 9 06 26 PM" src="https://github.com/4darsh-Dev/CogniGaurd/assets/103454929/70ea4c1e-0ece-4393-a99f-eb81b7b1c732">

<img width="223" alt="Screenshot 2024-06-08 at 9 16 31 PM" src="https://github.com/4darsh-Dev/CogniGaurd/assets/103454929/133a5339-6837-4d8b-9485-c158671770f9">

**Comment by 4darsh-Dev** [comment]
@Amishachoudhary22 designs looks nice, 
but there is already an issue for ui/ux you can give you design samples there i'll assign upon viewing the designs,
navbar position is fine on the RHS , just change the rest design and make it look more professional
