### ISSUE TITLE
Add login page

### ISSUE THREAD

**Issue by ayushrskiaa** [4darsh-Dev/CogniGaurd#69]
I can make a login page for this website
plaese assign me this issue.
Thank you

**Comment by 4darsh-Dev** [comment]
okay, propose the design @ayushrskiaa 
it have added basic login page, you can check on live link

**Comment by ayushrskiaa** [comment]
![We're](https://github.com/4darsh-Dev/CogniGaurd/assets/130389607/2b04a074-e612-40b1-8969-fc17440dc1d1)
This is my design.

**Comment by 4darsh-Dev** [comment]
background image doesn't look right, you are not forced to use only pre-selected images, 
you can choose images, vectors as per your choice .. 
take reference from there -> https://dribbble.com/tags/login-page

**Comment by ayushrskiaa** [comment]
![593bb87bf9a16fef09817d006b1b0b2e.png](https://github.com/4darsh-Dev/CogniGaurd/assets/130389607/ff2e9b94-6af6-40a6-bb0c-4f9201eee4e2)

Is it good?

**Comment by 4darsh-Dev** [comment]
@ayushrskiaa much better design. just match the color pallete of the website you can find named as font-primary and font-secondary in style.css in  django-web-app/static/css/ directory

again great work .

**Comment by ayushrskiaa** [comment]
thanks @4darsh-Dev

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@4darsh-Dev

**Comment by 4darsh-Dev** [comment]
@TheNikhilRaj  assigned to you, 
see contributing guidelines and notices pinned in issue section

**Comment by TheNikhilRaj** [comment]
@4darsh-Dev I have done the changes.

Uploading 20240623224611.mp4…

**Comment by TheNikhilRaj** [comment]
@4darsh-Dev I have done the changes.

Uploading 20240623224611.mp4…

**Comment by TheNikhilRaj** [comment]
@4darsh-Dev 
I have done the changes!

https://github.com/4darsh-Dev/CogniGaurd/assets/129590267/0708f72e-c2a9-4fbe-8049-2803c8e522c3

**Comment by 4darsh-Dev** [comment]
@TheNikhilRaj  good work, 
Someone already fixed it few hours ago, 
You can work on other issues.

**Comment by 4darsh-Dev** [comment]
Hey @ayushrskiaa ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
