### ISSUE TITLE
[URGENT]Web App is Not Compatible with Small Screen Devices

### ISSUE THREAD

**Issue by codercake** [4darsh-Dev/CogniGaurd#70]
The web application is not responsive, causing layout issues when viewed on different screen sizes, particularly on mobile devices. Elements are overlapping, text is misaligned, and the user experience is significantly affected.

**What happened?**
When accessing the web app on a mobile device or a smaller screen, the layout does not adjust appropriately. This results in overlapping text, misplaced elements, and a generally cluttered and unusable interface.

**Expected Behavior:**
The web app should be responsive and adjust its layout based on the screen size. Elements should be properly aligned, text should be readable, and the interface should be user-friendly on all devices.

**Steps to Reproduce:**
1. Open the web application on a mobile device or a small screen.
2. Navigate through different sections of the app.
3. Observe the layout issues and overlapping elements.

**Screenshots:**
![Screenshot 2024-06-09 150057](https://github.com/4darsh-Dev/CogniGaurd/assets/117517206/e4d82d33-20b1-43bb-8914-7bd6d12b901c)

**Additional Information:**
- **Device:** Mobile or small screen device
- **Browser:** Any
- **OS:** Any

 **Record**
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue
- [x] I agree to follow this project's Code of Conduct

**Comment by 4darsh-Dev** [comment]
@codercake  actually there is an already issue similar to this, 
if you want to work on it, look the pinned issues, and ask there i'll assign to you, 
you can work on it .

**Comment by codercake** [comment]
I've looked at the pinned issue. Can I simultaneously work on it so you can choose the solution that best fits your requirements?

**Comment by 4darsh-Dev** [comment]
okay @codercake assigned to you,

**Comment by 4darsh-Dev** [comment]
i'll assign level after seeing, how significant your contribution is.

**Comment by 4darsh-Dev** [comment]
@codercake any work update? 
this issue is urgent causing problems to a lot of users. 
if you are unable to work on this please clearify.

**Comment by 4darsh-Dev** [comment]
explain the issue, i'll help you out, share the screenshot for the reference

**Comment by codercake** [comment]
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/117517206/763a3f0a-833b-41e8-a273-db3d9ec4213c)

**Comment by 4darsh-Dev** [comment]
Turn Debug = True in settings.py file ( for production only) to see the reason for error .

**Comment by codercake** [comment]
alright, let me check.

**Comment by 4darsh-Dev** [comment]
if the error says something like project key is missing : then comment the line with 
secret_key = "" 
2. in settings.py databases section  comment out the previous database and use default sqlite3 database 
3. in cogniguard/urls.py comment the vercel deployment static url link 

-- i'm updating these change in the readme as well you can take reference from there.

**Comment by codercake** [comment]
> if the error says something like project key is missing : then comment the line with secret_key = "" 2. in settings.py databases section comment out the previous database and use default sqlite3 database 3. in cogniguard/urls.py comment the vercel deployment static url link
> 
> -- i'm updating these change in the readme as well you can take reference from there.

i've made the changes according to the comprehensive readme, it's still the same after updating urls.py and settings.py 
![Screenshot 2024-06-15 181027](https://github.com/4darsh-Dev/CogniGaurd/assets/117517206/22b947ac-7247-4666-a002-7b274544e267)
![Screenshot 2024-06-15 181046](https://github.com/4darsh-Dev/CogniGaurd/assets/117517206/15c570c6-488d-42e3-90f2-572fb8014f03)

**Comment by 4darsh-Dev** [comment]
@codercake if the debug= True then it should give detailed reason, 
In SS attached it is saying that server has started already.
It might be due to database configuration, share ss
:: Remember you're the admin if setting up project locally, so check for any misconfiguration.

**Comment by 4darsh-Dev** [comment]
Hey @codercake ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
