### ISSUE TITLE
Fix the Readme file

### ISSUE THREAD

**Issue by sristy17** [4darsh-Dev/CogniGaurd#72]
Fix the Readme file, add and modify some more features.
![Screenshot from 2024-06-10 19-21-40](https://github.com/4darsh-Dev/CogniGaurd/assets/136837204/e7bddf17-c380-4740-a98c-344fa0c8c6da)

**Comment by 4darsh-Dev** [comment]
Hey @sristy17 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
