### ISSUE TITLE
Adding of Google Auth

### ISSUE THREAD

**Issue by mukilan2815** [4darsh-Dev/CogniGaurd#73]
**Is your feature request related to a problem? Please describe.**
I used to login with only one click using google . But this option is not here in this project. 

**Describe the solution you'd like**
We can add google option for signing in and users can login without need to type and remember the password.

![image](https://github.com/4darsh-Dev/CogniGaurd/assets/71129858/c250445a-f30d-4666-80f6-bde3f249a09a)

**Additional context**
Please add this under GSSOC'24. As this is backend change please assign level 3

**Comment by 4darsh-Dev** [comment]
okay @mukilan2815 i can assign this to you, 
have you worked on django before or setting up google oauth ?
first have a look at codebase, you have to follow the code guidelines and client id and google oauth secret keys use as environment variables,

**Comment by mukilan2815** [comment]
@4darsh-Dev I have experience in django as I built ecommerce sites before. Assign this to me I can finish this for sure. Please assign under GSSOC'24 LEVEL3

**Comment by 4darsh-Dev** [comment]
okay assigned to you @mukilan2815, update me if you have any queries ?

**Comment by 4darsh-Dev** [comment]
see the notice in pinned in issue if you are facing any difficulty with project local setup

**Comment by mukilan2815** [comment]
Yeah... I will complete this soon

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
Hey @mukilan2815 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
