### ISSUE TITLE
 Implement Closed Greeting Message

### ISSUE THREAD

**Issue by thevijayshankersharma** [4darsh-Dev/CogniGaurd#74]
To enhance user experience and maintain consistency in communication, we should implement a closed greeting message for issues that have been resolved. This message will serve as a polite acknowledgment to the user that their issue has been addressed and encourage them to reach out again if they encounter any further concerns. Let's discuss and finalize the content and placement of this closed greeting message to ensure it aligns with our user engagement goals.

**Comment by 4darsh-Dev** [comment]
great, 
assigned to you @thevijayshankersharma

**Comment by 4darsh-Dev** [comment]
Hey @thevijayshankersharma ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
