### ISSUE TITLE
[UI/UX] Adding a preloader for the web app

### ISSUE THREAD

**Issue by 4darsh-Dev** [4darsh-Dev/CogniGaurd#75]
### Changes to be made
1. Adding a website preloader using css and js which is good looking and also matches with color palletes.
2. Propose the design first
3. Task will be assigned after seeing your proposals. 

### Additional info
1. Take reference from here - https://htmlburger.com/blog/website-preloaders/
2. You can propose your own creative designs as well.

**Comment by 4darsh-Dev** [comment]
great @AsmitaMishra24, 
assigned to you, try to match the primary colour code of the website, 
see CSS variables for reference

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
any work update @AsmitaMishra24 ?

**Comment by AsmitaMishra24** [comment]
> any work update @AsmitaMishra24 ?

@4darsh-Dev, I will submit the PR by tomorrow.

**Comment by 4darsh-Dev** [comment]
sure @AsmitaMishra24 
let me know if you're facing any issues

**Comment by AsmitaMishra24** [comment]
> sure @AsmitaMishra24 let me know if you're facing any issues

@4darsh-Dev, I am getting an error of client-id so how can I create my client-id

**Comment by 4darsh-Dev** [comment]
@AsmitaMishra24 , 
actually client-id is used for feature of Oauth login with google, 
google provides it in console management, 
you can just create a .env file in django-web-app directory  with a dummy value, it should remove the missing error 
see readme

**Comment by 4darsh-Dev** [comment]
any update @AshmitaBarthwal ?

**Comment by Dharmi-dev** [comment]
I am very excited to work on this issue with you,
I will make pretty preloader according to the primary colours of the website
please assign this issue to me

**Comment by Dharmi-dev** [comment]
![Screenshot 2024-07-20 104300](https://github.com/user-attachments/assets/68840e2c-0733-4ed6-a964-6a15788740e8)
![Screenshot 2024-07-20 105749](https://github.com/user-attachments/assets/c7f8e6e2-4ef6-4c6a-a0c1-c9f4cfdbef29)

**Comment by AsmitaMishra24** [comment]
@4darsh-Dev, My laptop is experiencing some issues...so you can assign this to @Dharmi-dev

**Comment by 4darsh-Dev** [comment]
assigned to you @Dharmi-dev , 
go through readme.md and contrib.md for project setup and guidelines. 
share the video preview then raise the pr.
