### ISSUE TITLE
Hover effect color in nav section & adding hover effects in footer 

### ISSUE THREAD

**Issue by aanchalpahuja18** [4darsh-Dev/CogniGaurd#76]
The color of hover effects in nav section is not pleasing & footer doesn't consists of hover effects on the links & the social media icons.

**Comment by aanchalpahuja18** [comment]
@4darsh-Dev kindly assign this issue to me I will resolve it really quick.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
Hey @aanchalpahuja18 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
