### ISSUE TITLE
changing styles and font 

### ISSUE THREAD

**Issue by Ishmeetkaur36** [4darsh-Dev/CogniGaurd#79]
The website seems too basic. Adding some styles and font changes could make it more attractive

**Comment by 4darsh-Dev** [comment]
@Ishmeetkaur36  propose you design and make it more attractive .

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
Hey @Ishmeetkaur36 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
