### ISSUE TITLE
Feature ✨: Add scroll to top button

### ISSUE THREAD

**Issue by Tejashri-Taral** [4darsh-Dev/CogniGaurd#80]
Hey @4darsh-Dev ,
I have noticed a small issue that I believe could enhance the user experience. Currently, there is no scroll to top button present on the website, which makes navigation a bit cumbersome, especially when users need to return to the top of a lengthy page.
Though it may seem minor, the absence of this feature can impact the overall usability and performance of the website.

******Screenshot(Mandatory):******

![image](https://github.com/4darsh-Dev/CogniGaurd/assets/160386036/2a95bcea-4b73-4a77-961d-faac30bbcea7)

@4darsh-Dev ,Could you please assign me this issue under gssoc'24 ?

Are you contributing under any open-source program ?
GSSOC'24

**Comment by 4darsh-Dev** [comment]
assigned to you @Tejashri-Taral

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue, please assign this to me.
@4darsh-Dev

**Comment by 4darsh-Dev** [comment]
assigned to you @TheNikhilRaj

**Comment by TheNikhilRaj** [comment]
@4darsh-Dev 
I have add the Add scroll to top button!

https://github.com/4darsh-Dev/CogniGaurd/assets/129590267/6c63e4c6-c05e-4e19-bb70-c5d362b39a47

**Comment by 4darsh-Dev** [comment]
okay, raise the PR 
i'll review it. 
Change color to --color-primary to match color palette.
You can add a  circular progress bar on it which increases as user scrolls from top to bottom and vice-versa, 
Much better. 
https://codewithfaraz.com/img/scroll-to-top%20button%20with%20progress%20indicator%20using%20html,%20css,%20and%20javascript.jpg

**Comment by TheNikhilRaj** [comment]
> okay, raise the PR i'll review it. Change color to --color-primary to match color palette. You can add a circular progress bar on it which increases as user scrolls from top to bottom and vice-versa, Much better. https://codewithfaraz.com/img/scroll-to-top%20button%20with%20progress%20indicator%20using%20html,%20css,%20and%20javascript.jpg

yes, i have raise the PR now you can check it!
@4darsh-Dev

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
Hey @Tejashri-Taral ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
