### ISSUE TITLE
navbar for mobile and tab and welcome page

### ISSUE THREAD

**Issue by anurag6569201** [4darsh-Dev/CogniGaurd#84]
Hello,
I wanted to add the navbar for the tab and mobile version because theirs a vertical navbar on the pc version so that i have modified for the tab version and navbar version

i have maked whole welcome page responsive for the tab mobile and pc

## pc version
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/140162738/13cec26d-11cb-4b32-83bf-865577440398)

## tab version
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/140162738/4dbbdea0-0082-40aa-8942-a222721295c1)

## mobile version
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/140162738/e506fe8e-0f38-493d-adf8-4da595908eae)

**Comment by anurag6569201** [comment]
@4darsh-Dev  kindly assign it as a level 3 under gssoc i have done coding i will push it as you assign it to me !!

**Comment by 4darsh-Dev** [comment]
assigned to you @anurag6569201 
have a look on contributing.md before raising the pr

**Comment by 4darsh-Dev** [comment]
Hey @anurag6569201 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
