### ISSUE TITLE
documentaion: no proper techstack

### ISSUE THREAD

**Issue by Debayan-Ghosh2005** [4darsh-Dev/CogniGaurd#89]
there is no proper maintain techstack row . i wil make it  properly for user can find it our code

**Comment by Debayan-Ghosh2005** [comment]
i am new at gssoc24 . can you assigned it to me

**Comment by 4darsh-Dev** [comment]
share SS or any preview of how it will look after doing changes.

**Comment by Debayan-Ghosh2005** [comment]
![Screenshot 2024-06-14 213345](https://github.com/4darsh-Dev/CogniGaurd/assets/149896687/7a53c1e9-4802-4646-a7d1-0c46bd6123a5)

**Comment by 4darsh-Dev** [comment]
Hey @Debayan-Ghosh2005 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
