### ISSUE TITLE
Sidebar UI 

### ISSUE THREAD

**Issue by vaishnavip27** [4darsh-Dev/CogniGaurd#90]
**Describe the bug**
The sidebar's height needs to be increased as the items are getting overflooded out of the div

**Expected behavior**
The height of the sidebar needs to be increased so the div's get adjusted in the parent component

**Screenshots**
![image](https://github.com/4darsh-Dev/CogniGaurd/assets/143169451/e8bb28bf-c8c8-4388-82e6-5738659bcf64)

**Additional context**

**Comment by vaishnavip27** [comment]
@4darsh-Dev Kindly assign me this issue

**Comment by 4darsh-Dev** [comment]
@vaishnavip27 another contributor just made a pr for responsiveness, 
check if the issue persists still i'll assign it to you.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
Hey @vaishnavip27 ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
