### ISSUE TITLE
Add hover effect in this section

### ISSUE THREAD

**Issue by arpit4521** [4darsh-Dev/CogniGaurd#93]
![Screenshot 2024-06-16 065828](https://github.com/4darsh-Dev/CogniGaurd/assets/127679958/97cc8ff4-d39d-454b-a5b0-0e91de728310)

hover effect is there in subscribe button but in these sections which is no looking synced together
@4darsh-Dev please assign this issue to me under gssoc and apt level label

**Comment by 4darsh-Dev** [comment]
@arpit4521  propose you changes or share some preview, 
if the change is minor then you'll get only +1 points , no levels

**Comment by arpit4521** [comment]
not able to clone the repo showing error error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2291 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
