### ISSUE TITLE
Add Hover effect into the footer icons.

### ISSUE THREAD

**Issue by chakrabortydeep** [4darsh-Dev/CogniGaurd#95]
![Screenshot 2024-06-16 213535](https://github.com/4darsh-Dev/CogniGaurd/assets/146315717/f0ca1500-415d-4b6a-b3e0-7a305e555770)

I can add hover effect into the icons to make it more interactive. I am an efficient coder and can make it effectively.

**Comment by 4darsh-Dev** [comment]
@chakrabortydeep hover effect already exists.

**Comment by 4darsh-Dev** [comment]
Hey @chakrabortydeep ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
