### ISSUE TITLE
[VSoC] Adding resposiveness on register page of web app for small screen devices

### ISSUE THREAD

**Issue by 4darsh-Dev** [4darsh-Dev/CogniGaurd#98]
### Changes to be made
1. Make register page responsive and maintain design aspects on mobile and i-pad devices,
2. use css media queries with appropriate break points and adjust font-size and elements size accordingly.
3. You can add additional breakpoints when needed. 
4. You have to make changes in django-web-app directory and read the local setup notice carefully pinned in issues. 

### Additional Context
1. Share preview or  SS of your changes.

**Comment by Asymtode712** [comment]
@4darsh-Dev Hey Adarsh, is the issues labelled by "VSoC'24" and authored by you are only meant for VSoC'24 contributors or a GSSoC'24 cotributor can also claim those??

**Comment by 4darsh-Dev** [comment]
@Asymtode712 these are only for vsoc contributors, 
there are many issues for gssoc contributors you can explore..

**Comment by 4darsh-Dev** [comment]
Hey @4darsh-Dev ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
