### ISSUE TITLE
Bettering the homepage data 

### ISSUE THREAD

**Issue by Mehak-Mattoo** [4darsh-Dev/CogniGaurd#99]
The information about the website can be beautifully explained in form of cards using react - vertical timeline for animation

**Comment by 4darsh-Dev** [comment]
@Mehak-Mattoo  propose the design preview or SS for the landing page, 
Currently our tech stack doesn't include react, so it will be better if you use vanilla js. 
Be sure other contributors are working on this too, so you've to be more efficient.

**Comment by Mehak-Mattoo** [comment]
Sure.

**Comment by 4darsh-Dev** [comment]
@Mehak-Mattoo any work update?

**Comment by Mehak-Mattoo** [comment]
Working on it

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
⚠️[URGENT]⚠️ Reminder for GSSoC 24' Contributors Please join our CogniGuard Project #general GSSoC'24 Discord channel:
 Here you can discuss your queries and doubts with your mentors. 
 See #109 issues section.

**Comment by 4darsh-Dev** [comment]
Hey @Mehak-Mattoo ! Thank you so much for your raising the issue💗 
 It’s all yours, you can come anytime again and make some contributions! 🚀 
 Alone, we can do little, but together we can do so much! 😇
